version: "3.9"
services:
  api:
    restart: unless-stopped
    image: "hivetown/backend:main"
    depends_on:
      - watchtower
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
    env_file:
      - api.env
  web:
    restart: unless-stopped
    image: "hivetown/frontend:main"
    depends_on:
      - watchtower
      - api
    ports:
      - "8081:80"
    env_file:
      - web.env
  service-discovery:
    depends_on:
      - api
      - web
    restart: unless-stopped
    build: ./service-discovery/
    environment:
      - API_PORT=8080
      - WEB_PORT=8081
    env_file:
      - .env
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
