version: "3.9"
services:
  api:
    restart: unless-stopped
    image: "luckspt/hivetown-api:latest"
    ports:
      - "8080:3000"
    environment:
      - "PORT=3000"
      - "MIKRO_ORM_HOST=localhost"
      - "MIKRO_ORM_PORT=3306"
      - "MIKRO_ORM_USER=root"
      - "MIKRO_ORM_PASSWORD=hello"
      - "MIKRO_ORM_DB_NAME=hivetown"
      - "MIKRO_ORM_DEBUG=true"
  web:
    restart: unless-stopped
    image: "luckspt/hivetown-web:latest"
    ports:
      - "8081:8080"
    environment:
      - "PORT=8080"