version: "3.9"
services:
  api:
    restart: unless-stopped
    image: "luckspt/hivetown-api:latest"
    ports:
      - "8080:3000"
    environment:
      - "PORT=3000"
  web:
    restart: unless-stopped
    image: "luckspt/hivetown-web:latest"
    ports:
      - "8081:8080"
    environment:
      - "PORT=8080"
  service-discovery:
    depends_on:
      - api
      - web
    restart: unless-stopped
    build: ./service-discovery/
    environment:
      - API_PORT=8080
      - WEB_PORT=8081
