version: "3.9"
services:
  api:
    restart: unless-stopped
    image: "luckspt/hivetown-api:latest"
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
    env_file:
      - api.env
  web:
    restart: unless-stopped
    image: "luckspt/hivetown-web:latest"
    ports:
      - "8081:80"
    env_file:
      - web.env
    depends_on:
      - api
  service-discovery:
    depends_on:
      - api
      - web
    restart: unless-stopped
    build: ./service-discovery/
    environment:
      - API_PORT=8080
      - WEB_PORT=8081
    env_file:
      - .env
