# Use the official HAProxy Alpine image
FROM haproxytech/haproxy-alpine:2.7.6

# Copy the configuration files
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

# Expose the ports
EXPOSE 80 443 1936
