version: '3.9'

services:
  load-balancer:
    build: .
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '4444:4444'
    networks:
      load-balancer:
        aliases:
          - load-balancer.local
    hostname: load-balancer.local
  service-discovery:
    build: ./service-discovery/
    restart: always
    networks:
      - load-balancer
    environment:
      - ZOOKEEPER_HOSTS=192.168.1.89:2181
      - HAPROXY_ADDRESS=http://192.168.1.89:4444
      - HAPROXY_USERNAME=admin
      - HAPROXY_PASSWORD=password
    depends_on:
      - load-balancer

networks:
  load-balancer:
    name: load-balancer
    driver: bridge
