version: '3.9'

services:
  load-balancer:
    build: .
    restart: always
    ports:
      - '80:80'
      - '443:443'
      # - '4444:4444'
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - load-balancer
  service-discovery:
    build: ./service-discovery/
    restart: always
    networks:
      - load-balancer
    environment:
      - HAPROXY_ADDRESS=http://load-balancer:4444
    env_file:
      - .env
    depends_on:
      - load-balancer
  letsencrypt:
    image: certbot/certbot
    deploy:
      restart_policy:
        condition: any
        delay: 24h
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - load-balancer
    depends_on:
      - load-balancer
    command: certonly --test-cert --standalone -d ${CERTBOT_DOMAINS} --non-interactive --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --http-01-port=8888
    env_file:
      - .env
networks:
  load-balancer:
    name: load-balancer
    driver: bridge
