version: '3.9'

services:
  load-balancer:
    build: .
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '4444:4444'
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - load-balancer
  service-discovery:
    build: ./service-discovery/
    restart: always
    networks:
      - load-balancer
    environment:
      - HAPROXY_ADDRESS=http://load-balancer:4444
    env_file:
      - .env
    depends_on:
      - load-balancer
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - load-balancer
    depends_on:
      - load-balancer
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${CERTBOT_DOMAINS}
    env_file:
      - .env
networks:
  load-balancer:
    name: load-balancer
    driver: bridge
