-- TODO template
CHANGE MASTER TO
    MASTER_HOST=${MYSQL_MASTER_HOST},
    MASTER_USER=${REPLICATOR_USER_USERNAME}, 
    MASTER_PASSWORD=${REPLICATOR_USER_PASSWORD},
    MASTER_PORT=3306,
    MASTER_LOG_FILE=${MYSQL_MASTER_LOG_FILE},
    MASTER_LOG_POS=0;
START SLAVE;